services:
  nginx:
    depends_on: !reset []

  node:
    image: node:20
    working_dir: /app
    networks:
      - app
    volumes:
      - .:/app
    # we don't want this service to start.
    # See https://stackoverflow.com/a/77001347/2502647 for details.
    profiles:
      - dummy-profile
