services:
# https://docs.docker.com/compose/compose-file/13-merge/#reset-value
  phpfpm: !reset []
  mail: !reset []
  mariadb: !reset []

  nginx:
    depends_on: !reset []

  node:
    image: node:20
    command: npm run dev
    working_dir: /app
    networks:
      - app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated
